name             'chef-frontend'
maintainer       'Abdul Hagi'
maintainer_email 'muridiv.1@gmail.com'
license          'All rights reserved'
description      'Installs/Configures chef-frontend'
long_description 'Installs/Configures chef-frontend'
version          '0.1.0'
